build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
  i386: "ghcr.io/home-assistant/i386-base-debian:bullseye"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Apache with mod-auth-openidc"
  org.opencontainers.image.description: >-
    Apache web server and reverse proxy with support for OpenID Connect authentication, powered by mod-auth-openidc.
  org.opencontainers.image.source: "https://github.com/chrisx8/home-assistant-addons/tree/main/apache-oidc"
  org.opencontainers.image.licenses: "MIT License"
