build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Tailscale"
  org.opencontainers.image.description: "Zero config VPN for building secure networks."
  org.opencontainers.image.source: "https://github.com/chrisx8/home-assistant-addons/tree/main/tailscale"
  org.opencontainers.image.licenses: "MIT License"
codenotary:
  base_image: notary@home-assistant.io
  signer: info+addons@chrisx.xyz
