name: Tailscale
version: 1.42.0
slug: tailscale
image: "ghcr.io/chrisx8/hassio-tailscale-{arch}"
description: Zero config VPN for building secure networks
url: https://github.com/chrisx8/hassio-addons/tree/main/tailscale
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armv7
init: false
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
options:
  accept_dns: false
  advertise_exit_node: false
  advertise_routes: []
schema:
  accept_dns: bool
  advertise_exit_node: bool
  advertise_routes:
    - str
