name: Tailscale
version: 1.24.2
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/chrisx8/home-assistant-addons/tree/main/tailscale
startup: services
panel_icon: mdi:vpn
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
host_network: true
