---
name: builder (rebuild all)
on:
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      addons_list: ${{ steps.addons.outputs.addons_list }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master
  build:
    needs: init
    runs-on: ubuntu-latest
    name: Build ${{ matrix.addon }} (${{ matrix.arch }})
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.addons_list) }}
        arch: ["aarch64", "amd64"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"
      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
            echo "build_arch=true" >> "$GITHUB_OUTPUT"
            echo "image=$(echo ${{ steps.info.outputs.image }} | cut -d'/' -f3)" >> "$GITHUB_OUTPUT"
          else
            echo "${{ matrix.arch }} is not a valid arch for ${{ matrix.addon }}, skipping build";
            echo "build_arch=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@2024.08.1
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --image "${{ steps.check.outputs.image }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
